name = "cloudflare-docker-proxy2"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "tdm.qzz.io"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy2"
# routes = [
#   { pattern = "docker.tdm.qzz.io", custom_domain = true },
#   { pattern = "quay.tdm.qzz.io", custom_domain = true },
#   { pattern = "gcr.tdm.qzz.io", custom_domain = true },
#   { pattern = "k8s-gcr.tdm.qzz.io", custom_domain = true },
#   { pattern = "k8s.tdm.qzz.io", custom_domain = true },
#   { pattern = "ghcr.tdm.qzz.io", custom_domain = true },
#   { pattern = "cloudsmith.tdm.qzz.io", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy2-staging"
# route = { pattern = "docker-staging.tdm.qzz.io", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
